/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package des;

import java.util.Scanner;

public class App {

	public static void main(String[] args) {
		Scanner scanner = new Scanner(System.in);

		System.out.println("Test Input");

		while (scanner.hasNextLine()) {
			String input = scanner.nextLine();
			System.out.println(input);
		}

		scanner.close();
	}
}
